In [1]:
import numpy as np

Генерация массива без сида (меняется при каждом запуске программы)

In [2]:
arr_wo_seed = np.random.randint(0,200,7)
arr_wo_seed

array([ 81, 163, 110,  68, 179,  22,  83])

Генерация массива с сидом (последовательность случ. чисел фиксируется)

In [3]:
np.random.seed(333)
arr_w_seed = np.random.randint(0,199,8)

In [4]:
arr_w_seed

array([ 12, 163, 179, 110, 118,  46, 188,  29])

Вывод макс. значения

In [5]:
arr_w_seed.max()

np.int64(188)

Вывод мин. значения

In [6]:
arr_w_seed.min()

np.int64(12)

Среднее арифметическое всех элементов массива

In [7]:
arr_w_seed.mean()

np.float64(105.625)

Индекс минимального элемента массива

In [8]:
arr_w_seed.argmin()

np.int64(0)

Индекс максимального элемента массива

In [9]:
arr_w_seed.argmax()

np.int64(6)

Изменить форму массива (нельзя указывать параметры x-строк и y-столбцов такие, что x*y != размер массива)

In [10]:
arr_w_seed.reshape(4,2)

array([[ 12, 163],
       [179, 110],
       [118,  46],
       [188,  29]])

In [11]:
arr_w_seed.reshape(5,2)

ValueError: cannot reshape array of size 8 into shape (5,2)

Создать двумерный массив размером x на y, заполненный случайными числами из стандарт. нормального распред.

In [12]:
arr = np.random.randn(3,3)
arr

array([[-0.81058483, -1.36428529,  0.45644073],
       [ 0.08592951,  2.2317828 , -0.54032917],
       [ 0.85372722, -1.70670445,  0.45431539]])

Создать одномерный массив длинной x (числа распределены по станд. нормальному распред.)

In [14]:
first = np.random.randn(3)
first

array([0.56194934, 1.59436817, 0.19915635])

Возвращает картеж с размерами по каждому измерению массива

In [16]:
first.shape

(3,)

In [17]:
second = np.random.randn(3)
second

поэлементное перемножение элементов

In [19]:
(first*second)

array([ 0.10640254,  1.79712682, -0.07066902])

суммирование элементов получившегося массива

In [21]:
(first*second).sum()

np.float64(1.8328603447176814)

скалярное произведение

In [22]:
np.dot(first,second)

np.float64(1.8328603447176814)

скалярное произведение по-другому

In [23]:
first.dot(second)

np.float64(1.8328603447176814)

создание матрицы из одномерного массива

In [34]:
mat = np.arange(0,10).reshape(2,5)
mat

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Обратиться к элементу матрицы по координатам

In [27]:
row = 1
col = 3

In [28]:
mat[row,col]

np.int64(8)

Превращаем столбец из матрицы и превращает его из вектора в столбец-матрицу

In [32]:
mat[:,col].reshape(-1, 2)

array([[3, 8]])

Вернуть весь столбец с индексом col

In [33]:
mat[:,col]

array([3, 8])

Срез массива

In [35]:
mat[0:1,0:2]

array([[0, 1]])